---
title: "Latency Model results"
author: "David Ferreira Quaresma (david.quaresma@ccc.ufcg.edu.br)"
date: "set, 2025"
output: pdf_document
---

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
source("utils.R")

functions_to_plot <- c(
    "bernoulli_9510-const_5.0",
    "bernoulli_9910-const_5.0",

    "weibull_k05λ5-const_5.0",
    "weibull_light-const_5.0",
    "weibull_medium-const_5.0",
    "weibull_heavy-const_5.0",

    "lognormal_mu1sig1-const_5.0",
    "lognormal_super-const_5.0",
    "lognormal_extreme-const_5.0"
)

simple_results_path = "/Users/davidquaresma/Desktop/repos/faas-simulator/sim_results/latency_model/"
simple_df = read.csv(paste(simple_results_path, "simple_model-full-results.csv", sep="")) %>% arrange(end_timestamp)
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
source("utils.R")
for (i in 1:length(functions_to_plot)) {
  print(plot_histogram_fullview(
    filter(filter(simple_df, func == functions_to_plot[i]), technique == "baseline")$service_time,
    paste("Histogram of service_time for", functions_to_plot[i], sep=" "),
    c("#53B0E6", "#FFB86B", "#0000CC", "#CC5500",
      "darkblue", "saddlebrown", "#53B0E6", "#FFB86B")
  ))
}
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
generate_improvement_table <- function(df) {
  scenario <- c()
  techniques <- c("hedged_requests_nodelay", "hedged_requests_p95", "hedged_requests_p99", "near_perfect_hedged_requests", "perfect_hedged_requests", "naive_hedge", "delayed_naive_hedge")
  response_time <- new.env(hash = TRUE, parent = emptyenv())
  time_running_funcs <- new.env(hash = TRUE, parent = emptyenv())
  imprvmnt <- new.env(hash = TRUE, parent = emptyenv())
  for (func_name in functions_to_plot) {
    scenario <- append(scenario, paste(func_name, "response_time", sep=": "))
    scenario <- append(scenario, paste(func_name, "total_time_running_functions", sep=": "))
    response_time[["baseline"]] <- sum(filter(simple_df, func == func_name, technique == "baseline")$response_time)
    time_running_funcs[["baseline"]] = sum(filter(simple_df, func == func_name, technique == "baseline")$total_time_running_functions)
    for (tech in techniques) {
      response_time[[tech]]      <- sum(filter(df, func == func_name, technique == tech)$response_time)
      time_running_funcs[[tech]] <- sum(filter(df, func == func_name, technique == tech)$total_time_running_functions)
      imprvmnt[[tech]] <- append(imprvmnt[[tech]], percent_improvement(response_time[[tech]],      response_time[["baseline"]]))
      imprvmnt[[tech]] <- append(imprvmnt[[tech]], percent_improvement(time_running_funcs[[tech]], time_running_funcs[["baseline"]]))
    }
  }
  latency_table <- data.frame(
     scenario = scenario,
     n_delayed = imprvmnt[["delayed_naive_hedge"]],
     hr_nodelay = imprvmnt[["hedged_requests_nodelay"]],
     hr_p95 = imprvmnt[["hedged_requests_p95"]],
     hr_p99 = imprvmnt[["hedged_requests_p99"]],
     tied_request = imprvmnt[["near_perfect_hedged_requests"]],
     perfect = imprvmnt[["perfect_hedged_requests"]]
  )
  rm(techniques, scenario, response_time, time_running_funcs, imprvmnt)
  return(latency_table)
}

latency_table = generate_improvement_table(simple_df)

library(knitr)
library(kableExtra)
kable(
  filter(latency_table),
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE, 
  digits = 2,
  caption = "Simple Model Latency Improvement Table All"
) %>%
  add_header_above(c(" " = 1, "naive (n)" = 1, "hedged request (hr)" = 3, "optimal" = 2)) %>% 
  kable_styling(full_width = TRUE, position = "center") %>% 
  scroll_box(width = "100%", height = "400px")
```
