---
title: "Replica Model Results"
author: "David Ferreira Quaresma (david.quaresma@ccc.ufcg.edu.br)"
date: "set, 2025"
output: pdf_document
---

# Load Utils
```{r setup, include=FALSE}
source("utils.R")
```

# Read Azure Imput
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
load_sim_results <- function(results_path, file_sufix) {
  technique = "baseline"
  parameters = "_idletimeINF_tlprobp95"
  baseline_inf_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  parameters = "_idletime900.0_tlprobp95"
  baseline_15min_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  parameters = "_idletime0.0_tlprobp95"
  baseline_zero_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))

  technique = "hedged_request"
  parameters = "_idletimeINF_tlprobp95"
  hedged_request_inf_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  parameters = "_idletime900.0_tlprobp95"
  hedged_request_15min_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  parameters = "_idletime0.0_tlprobp95"
  hedged_request_zero_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))

  rm(sim_results_path)
  rm(technique)
  rm(parameters)
  rm(file_sufix)
  
  return(
    list(
      baseline_inf_input = baseline_inf_input,
      baseline_15min_input = baseline_15min_input,
      baseline_zero_input = baseline_zero_input,

      hedged_request_inf_input = hedged_request_inf_input,
      hedged_request_15min_input = hedged_request_15min_input,
      hedged_request_zero_input = hedged_request_zero_input
    )
  )
}

# make timestamp readable as human 
#df = azure_input
#df$target_timestamp = df$start_timestamp
#df$time_readable <- as.POSIXct(df$target_timestamp, origin = "2021-01-31", tz = "UTC")

functions_to_plot <- c(
  "155e47f8e7f751d0c845049456d01832013c61336a8cd85901330ac821a71534", # 535667 -> 535667
  "8ef9c2c907e9cd5fb4b5cb3bfbebca6d9a01bb1f65a0f476e3914cae25bd2aae", # 212755 -> 161085 (had zero duration entries)
  "cc5bb2108cc7daf53f9728ad21f661a8ef9c8b36284bacfcb712e2be87eef842", # 142856 -> 142856
  "4753d9ffc8a362eadfb27498581969561c0ddbec7257759dbcb9936e506aff82" # 124143 -> 124143
#  "89d488538f940c98367ff572230106d1089868bdd379d9e2b9755b679dc186d2", # 76093 -> 76093
#  "bd5be891d0d10fbc3c59215d5f8159ea496433bc41adba7d8d10ea21d35c3e3a", # 116130 -> 73464 (had zero duration entries)
#  "30aa434528bc68ee07745ee7be3a0bdb33d58961fdc8460ce5b5b46b4def96e8", # 71759 -> 71759
#  "b89efb5e9d1b7e5900ef441b098d4c8b01600af5e673a9f9d607b3598f0fe548", # 63506 -> 63506
#  "8e5f533dbf1092f56ac6c7542ef3bdec4661bd442c9b5e7537fabc7b8c03f5a8", # 53263 -> 53263
#  "c098bb74acb70a0ea1bce98a7090169f3be59a0758389a403d77592aa56ce596", # 41333 -> 41333
#  "eefb3a7b86d12c2676276a5dde28099ef6f546a60e5b78e0a1c2b7221baf154d"  # 41333 -> 3107 (had too many zero duration entries)
)
  
titles <- c(
  "func w/ suffix 534",
  "func w/ suffix aae", 
  "func w/ suffix 842",
  "func w/ suffix f82"
#  "func w/ suffix 6d2",
#  "func w/ suffix e3a", 
#  "func w/ suffix 6e8",
#  "func w/ suffix 548",
#  "func w/ suffix 5a8",
#  "func w/ suffix 596",
#  "func w/ suffix 54d"
)

azure_input = read.csv(paste(
  "/Users/davidquaresma/Desktop/repos/faas-simulator/traces/azure/",
  "AzureFunctionsInvocationTraceForTwoWeeksJan2021-processed.csv", sep="")
)
for (i in 1:length(functions_to_plot)) {
  azure_input_filtered = filter(azure_input, func == functions_to_plot[i])
  print(plot_requests_workload(azure_input_filtered, title=paste("Invocations for Function ", titles[i], sep="")))
}

## Plot Arrivals Rate
#library(fitdistrplus)
#for (i in 1:length(functions_to_plot)) {
#  generated_input_filtered = filter(generated_input, func == functions_to_plot[i])
#  print(plot_requests_workload(generated_input_filtered, title=paste("Invocations for Function ", titles[i], sep="")))
  #desc_dist <- descdist(generated_input_filtered %>% pull(duration), discrete = FALSE, boot = 500)
#}
#rm(generated_input_filtered)
```


```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
trace_results_path = "/Users/davidquaresma/Desktop/repos/faas-simulator/traces/generated/"
sim_results_path="/Users/davidquaresma/Desktop/repos/faas-simulator/sim_results/replica_model/generated/"

file_sufix = "-invocations.csv"
loaded = load_sim_results(sim_results_path, file_sufix)
baseline_inf_input = loaded$baseline_inf_input
baseline_15min_input = loaded$baseline_15min_input
baseline_zero_input = loaded$baseline_zero_input
hedged_request_inf_input = loaded$hedged_request_inf_input
hedged_request_15min_input = loaded$hedged_request_15min_input
hedged_request_zero_input = loaded$hedged_request_zero_input

baseline_inf_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_inf_input)$responseTimeToEvaluate
baseline_15min_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_15min_input)$responseTimeToEvaluate
baseline_zero_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_zero_input)$responseTimeToEvaluate
hedged_request_inf_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(hedged_request_inf_input)$responseTimeToEvaluate
hedged_request_15min_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(hedged_request_15min_input)$responseTimeToEvaluate
hedged_request_zero_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(hedged_request_zero_input)$responseTimeToEvaluate
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
scenario <- c()
baseline_latency <- c()
hedged_request_latency <- c()
percentage <- c()
for (i in 1:length(functions_to_plot)) {
  baseline_response = filter(baseline_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  hedged_request_response = filter(hedged_request_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  scenario <- append(scenario, paste("func", titles[i], "idletime-INF", sep="-"))
  baseline_latency <- append(baseline_latency, sum(baseline_response))
  hedged_request_latency <- append(hedged_request_latency, sum(hedged_request_response))
  percentage <- append(percentage, (1-sum(hedged_request_response)/sum(baseline_response))*100)
  #print(summary_table(baseline_response, "baseline INF", hedged_request_response,"hedged_request INF"))

  baseline_response = filter(baseline_15min_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  hedged_request_response = filter(hedged_request_15min_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  scenario <- append(scenario, paste("func", titles[i], "idletime-15min", sep="-"))
  baseline_latency <- append(baseline_latency, sum(baseline_response))
  hedged_request_latency <- append(hedged_request_latency, sum(hedged_request_response))
  percentage <- append(percentage, (1-sum(hedged_request_response)/sum(baseline_response))*100)
  #print(summary_table(baseline_response, "baseline 15min", hedged_request_response,"hedged_request 15min"))
  
  baseline_response = filter(baseline_zero_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  hedged_request_response = filter(hedged_request_zero_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  scenario <- append(scenario, paste("func", titles[i], "idletime-zero", sep="-"))
  baseline_latency <- append(baseline_latency, sum(baseline_response))
  hedged_request_latency <- append(hedged_request_latency, sum(hedged_request_response))
  percentage <- append(percentage, (1-sum(hedged_request_response)/sum(baseline_response))*100)
  #print(summary_table(baseline_response, "baseline 15min", hedged_request_response,"hedged_request 15min"))
}
rm(baseline_response)
rm(hedged_request_response)

total_latency_table <- data.frame(
  scenario = scenario,
  baseline = baseline_latency,
  hedged_request = hedged_request_latency,
  improvement = percentage
)
#print(total_latency_table)
library(knitr)
library(kableExtra)
kable(total_latency_table, 
      format = if (knitr::is_latex_output()) "latex" else "html",
      booktabs = TRUE, 
      digits = 2,
      caption = "Latency Improvement Comparison") %>%
  kable_styling(full_width = FALSE, position = "center")


rm(baseline_latency)
rm(hedged_request_latency)
rm(percentage)
rm(total_latency_table)

rm(scenario)
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
file_sufix = "-replicas.csv"
loaded = load_sim_results(sim_results_path, file_sufix)
baseline_inf_input = loaded$baseline_inf_input
baseline_15min_input = loaded$baseline_15min_input
baseline_zero_input = loaded$baseline_zero_input
hedged_request_inf_input = loaded$hedged_request_inf_input
hedged_request_15min_input = loaded$hedged_request_15min_input
hedged_request_zero_input = loaded$hedged_request_zero_input
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
scenario <- c()
baseline_sumuptime <- c()
hedged_request_sumuptime <- c()
baseline_sumbusytime <- c()
hedged_request_sumbusytime <- c()
baseline_effy <- c()
hedged_request_effy <- c()
for (i in 1:length(functions_to_plot)) {
  scenario <- append(scenario, paste("func", titles[i], "idletime-INF", sep="-"))
  baseline_total = sum(filter(baseline_inf_input, funcID == functions_to_plot[i])$upTime)
  hedged_request_total = sum(filter(hedged_request_inf_input, funcID == functions_to_plot[i])$upTime)
  baseline_sumuptime <- append(baseline_sumuptime, baseline_total)
  hedged_request_sumuptime <- append(hedged_request_sumuptime, hedged_request_total)
  baseline_busy = sum(filter(baseline_inf_input, funcID == functions_to_plot[i])$busyTime)
  hedged_request_busy = sum(filter(hedged_request_inf_input, funcID == functions_to_plot[i])$busyTime)
  baseline_sumbusytime <- append(baseline_sumbusytime, baseline_busy)
  hedged_request_sumbusytime <- append(hedged_request_sumbusytime, hedged_request_busy)
  baseline_effy <- append(baseline_effy, baseline_busy/baseline_total*100)
  hedged_request_effy <- append(hedged_request_effy, hedged_request_busy/hedged_request_total*100)

  scenario <- append(scenario, paste("func", titles[i], "idletime-15min", sep="-"))
  baseline_total = sum(filter(baseline_15min_input, funcID == functions_to_plot[i])$upTime)
  hedged_request_total = sum(filter(hedged_request_15min_input, funcID == functions_to_plot[i])$upTime)
  baseline_sumuptime <- append(baseline_sumuptime, baseline_total)
  hedged_request_sumuptime <- append(hedged_request_sumuptime, hedged_request_total)
  baseline_busy = sum(filter(baseline_15min_input, funcID == functions_to_plot[i])$busyTime)
  hedged_request_busy = sum(filter(hedged_request_15min_input, funcID == functions_to_plot[i])$busyTime)
  baseline_sumbusytime <- append(baseline_sumbusytime, baseline_busy)
  hedged_request_sumbusytime <- append(hedged_request_sumbusytime, hedged_request_busy)
  baseline_effy <- append(baseline_effy, baseline_busy/baseline_total*100)
  hedged_request_effy <- append(hedged_request_effy, hedged_request_busy/hedged_request_total*100)
  
  scenario <- append(scenario, paste("func", titles[i], "idletime-zero", sep="-"))
  baseline_total = sum(filter(baseline_zero_input, funcID == functions_to_plot[i])$upTime)
  hedged_request_total = sum(filter(hedged_request_zero_input, funcID == functions_to_plot[i])$upTime)
  baseline_sumuptime <- append(baseline_sumuptime, baseline_total)
  hedged_request_sumuptime <- append(hedged_request_sumuptime, hedged_request_total)
  baseline_busy = sum(filter(baseline_zero_input, funcID == functions_to_plot[i])$busyTime)
  hedged_request_busy = sum(filter(hedged_request_zero_input, funcID == functions_to_plot[i])$busyTime)
  baseline_sumbusytime <- append(baseline_sumbusytime, baseline_busy)
  hedged_request_sumbusytime <- append(hedged_request_sumbusytime, hedged_request_busy)
  baseline_effy <- append(baseline_effy, baseline_busy/baseline_total*100)
  hedged_request_effy <- append(hedged_request_effy, hedged_request_busy/hedged_request_total*100)
  
}
rm(baseline_total)
rm(baseline_busy)
rm(hedged_request_total)
rm(hedged_request_busy)

total_effy_table <- data.frame(
  scenario = scenario,
  baseline_b = baseline_sumbusytime,
  hedged_request_b = hedged_request_sumbusytime,
  baseline_u = baseline_sumuptime,
  hedged_request_u = hedged_request_sumuptime,
  baseline_e = baseline_effy,
  hedged_request_e = hedged_request_effy
)
library(knitr)
library(kableExtra)
tab <- kable(
  total_effy_table,
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE,
  digits = 2,
  caption = "Replicas's Efficiency Usage"
)
tab %>%
  add_header_above(c(" " = 1, "Total Busy Time" = 2, "Total Up Time" = 2, "Efficiency" = 2)) %>%
  kable_styling(full_width = FALSE, position = "center")

rm(scenario)
rm(baseline_sumuptime)
rm(hedged_request_sumuptime)
rm(baseline_sumbusytime)
rm(hedged_request_sumbusytime)
rm(baseline_effy)
rm(hedged_request_effy)
rm(percentage)
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
trace_results_path = "/Users/davidquaresma/Desktop/repos/faas-simulator/traces/generated/"
generated_input = read.csv(paste(trace_results_path, "generated-trace-processed.csv", sep=""))
#generated_input$time_readable <- as.POSIXct(generated_input$target_timestamp, origin = "2021-01-31", tz = "UTC")

file_sufix = "-invocations.csv"
loaded = load_sim_results(sim_results_path, file_sufix)
baseline_inf_input = loaded$baseline_inf_input
baseline_15min_input = loaded$baseline_15min_input
baseline_zero_input = loaded$baseline_zero_input
hedged_request_inf_input = loaded$hedged_request_inf_input
hedged_request_15min_input = loaded$hedged_request_15min_input
hedged_request_zero_input = loaded$hedged_request_zero_input

baseline_inf_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_inf_input)$responseTimeToEvaluate
baseline_15min_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_15min_input)$responseTimeToEvaluate
baseline_zero_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_zero_input)$responseTimeToEvaluate
hedged_request_inf_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(hedged_request_inf_input)$responseTimeToEvaluate
hedged_request_15min_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(hedged_request_15min_input)$responseTimeToEvaluate
hedged_request_zero_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(hedged_request_zero_input)$responseTimeToEvaluate

functions_to_plot <- c(
    "bernoulli_9510-const_5.0",
    "weibull_k05λ5-const_5.0",
    "lognormal_mu1sig1-const_5.0"
)
titles <- functions_to_plot
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
for (i in 1:length(functions_to_plot)) {
  call_histograms(
    filter(generated_input, func == functions_to_plot[i])$duration,
    filter(baseline_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    paste(titles[i], "trace input", sep=" "),
    paste(titles[i], "baseline sim", sep=" "),
    paste("Sanity Check for ", titles[i], ": Generated vs Simulated", sep=""),
    c("#53B0E6", "#FFB86B", "#0000CC", "#CC5500", "darkblue", "saddlebrown")
  )
}
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
for (i in 1:length(functions_to_plot)) {
  call_histograms(
    filter(baseline_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    filter(hedged_request_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    paste(titles[i], "baseline sim", sep=" "),
    paste(titles[i], "hedged_request sim", sep=" "),
    paste("Comparison under Idletime INF for ", titles[i], ": Baseline vs hedged_request", sep=""),
    c("#FF6B6B", "#4ECDC4", "#CC0000", "#006B5B", "darkred", "darkslategray")
  )
}
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
for (i in 1:length(functions_to_plot)) {
  call_histograms(
    filter(baseline_15min_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    filter(hedged_request_15min_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    paste(titles[i], "baseline sim", sep=" "),
    paste(titles[i], "hedged_request sim", sep=" "),
    paste("Comparison under Idletime 15min for ", titles[i], ": Baseline vs hedged_request", sep=""),
    c("#FF6B6B", "#4ECDC4", "#CC0000", "#006B5B", "darkred", "darkslategray")
  )
}
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
file_sufix = "-provisioners.csv"
loaded = load_sim_results(sim_results_path, file_sufix)
baseline_inf_input = loaded$baseline_inf_input
baseline_15min_input = loaded$baseline_15min_input
baseline_zero_input = loaded$baseline_zero_input
hedged_request_inf_input = loaded$hedged_request_inf_input
hedged_request_15min_input = loaded$hedged_request_15min_input
hedged_request_zero_input = loaded$hedged_request_zero_input
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'}
### Plot Replicas Alive
#The plots show the number of active replicas over time for baseline vs hedged_request across all idletime configurations. The purpose is to understand whether hedged_request keeps more replicas alive and how that impacts resource usage. As expected for every function, hedged_request requires more simultaneous replicas. Fun observation is how idletime inf impact varies according to the function distribution latency.  

for (i in 1:length(functions_to_plot)) {
  print(
    plot_replicas_alive(
      bind_rows(
        baseline_inf = filter(baseline_inf_input, funcID == functions_to_plot[i]),
        hedged_request_inf = filter(hedged_request_inf_input, funcID == functions_to_plot[i]),
        baseline_15min = filter(baseline_15min_input, funcID == functions_to_plot[i]),
        hedged_request_15min = filter(hedged_request_15min_input, funcID == functions_to_plot[i]),
        baseline_zero = filter(baseline_zero_input, funcID == functions_to_plot[i]),
        hedged_request_zero = filter(hedged_request_zero_input, funcID == functions_to_plot[i]),
        .id = "scenario"
      ),
      c("baseline_inf", "hedged_request_inf", "baseline_15min", "hedged_request_15min", "baseline_zero", "hedged_request_zero"),
      scenario_col = "scenario",
      title = paste(titles[i], ": Replicas Active for Baseline vs hedged_request", sep="")
    )
  )
}
```
