---
title: "Playground for Exploration"
author: "David Ferreira Quaresma (david.quaresma@ccc.ufcg.edu.br)"
date: "set, 2025"
output: pdf_document
---

# Load Utils
```{r setup, include=FALSE}
source("utils.R")
```

# Load Data Grouping All Simulation Scenarios
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
#results_path <- "/Users/davidquaresma/Desktop/repos/faas-simulator/results_azure"
results_path <- "/Users/davidquaresma/Desktop/repos/faas-simulator/results_generator"
techs <- c('RequestHedgingOpt', 'Vanilla', 'GCI', 'RequestHedgingDefault')
probs <- c('tlprobp95', 'tlprobp99')
idletimes <- c('idletimeINF', 'idletime0.0', 'idletime900.0')

start_time <- Sys.time()
data_loaded <- load_data_summarized(results_path, techs, probs, idletimes)
invocations_df <- data_loaded$invocations_df
replicas_df <- data_loaded$replicas_df
end_time <- Sys.time()
print(paste("All Azure Simulation Load Time: ", end_time - start_time, sep=""))

rm(results_path)
rm(techs)
rm(probs)
rm(idletimes)
rm(data_loaded)
rm(start_time)
rm(end_time)
```

# Filter Function for Further Study
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
azure_functions_to_plot <- c(
  "155e47f8e7f751d0c845049456d01832013c61336a8cd85901330ac821a71534", # 535667 -> 535667
  "8ef9c2c907e9cd5fb4b5cb3bfbebca6d9a01bb1f65a0f476e3914cae25bd2aae", # 212755 -> 161085 (had zero duration entries)
  "cc5bb2108cc7daf53f9728ad21f661a8ef9c8b36284bacfcb712e2be87eef842", # 142856 -> 142856
  "4753d9ffc8a362eadfb27498581969561c0ddbec7257759dbcb9936e506aff82", # 124143 -> 124143
  "89d488538f940c98367ff572230106d1089868bdd379d9e2b9755b679dc186d2", # 76093 -> 76093
  "bd5be891d0d10fbc3c59215d5f8159ea496433bc41adba7d8d10ea21d35c3e3a", # 116130 -> 73464 (had zero duration entries)
  "30aa434528bc68ee07745ee7be3a0bdb33d58961fdc8460ce5b5b46b4def96e8", # 71759 -> 71759
  "b89efb5e9d1b7e5900ef441b098d4c8b01600af5e673a9f9d607b3598f0fe548" # 63506 -> 63506
)
azure_function_names <- c(
  "func w/ suffix 534",
  "func w/ suffix aae", 
  "func w/ suffix 842",
  "func w/ suffix f82",
  "func w/ suffix 6d2",
  "func w/ suffix e3a", 
  "func w/ suffix 6e8",
  "func w/ suffix 548"
)

generated_functions_to_plot <- c(
  "constant-bernoulli-func",
  "poisson-bernoulli-func",
  "constant-weibull-func",
  "poisson-weibull-func",
  "constant-logNormal-func",
  "poisson-logNormal-func"
)
generated_function_names <- c(
  "func constant-bernoulli",
  "func poisson-bernoulli",
  "func constant-weibull",
  "func poisson-weibull",
  "func constant-logNormal",
  "func poisson-logNormal"
)

selected_func_index = 1

#selected_func = azure_functions_to_plot[selected_func_index]
#func_title = azure_function_names[selected_func_index]
selected_func = generated_functions_to_plot[selected_func_index]
func_title = generated_function_names[selected_func_index]

invocations_df_filtered = filter(invocations_df, funcID == selected_func)
replicas_df_filtered = filter(replicas_df, funcID == selected_func)

rm(selected_func_index)
rm(selected_func)
rm(azure_functions_to_plot)
rm(azure_function_names)
rm(generated_functions_to_plot)
rm(generated_function_names)
```

# Plot Hist For Invocations/Replicas For All Azure Scenarios
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
plot_title =  "95th of invocations' response time for each idletime"
plot_hist_results(
  invocations_df_filtered,
  invocations_df_filtered$p95,
  "response time (ms)",
  paste(plot_title, func_title, sep=)
)
plot_title =  "95th of invocations' response time for each idletime (excluding idletime zero)"
plot_hist_results(
  invocations_df_filtered[invocations_df_filtered$idletime != 0, ],
  invocations_df_filtered[invocations_df_filtered$idletime != 0, ]$p95,
  "response time (ms)",
  paste(plot_title, func_title, sep=)
)

plot_title =  "99th of invocations' response time for each idletime"
plot_hist_results(
  invocations_df_filtered,
  invocations_df_filtered$p99,
  "response time (ms)",
  paste(plot_title, func_title, sep=)
)
plot_title =  "999th of invocations' response time for each idletime (excluding idletime zero)"
plot_hist_results(
  invocations_df_filtered[invocations_df_filtered$idletime != 0, ],
  invocations_df_filtered[invocations_df_filtered$idletime != 0, ]$p99,
  "response time (ms)",
  paste(plot_title, func_title, sep=)
)

plot_title =  "999th of invocations' response time for each idletime"
plot_hist_results(
  invocations_df_filtered,
  invocations_df_filtered$p999,
  "response time (ms)",
  paste(plot_title, func_title, sep=)
)
plot_title =  "999th of invocations' response time for each idletime (excluding idletime zero)"
plot_hist_results(
  invocations_df_filtered[invocations_df_filtered$idletime != 0, ],
  invocations_df_filtered[invocations_df_filtered$idletime != 0, ]$p999,
  "response time (ms)",
  paste(plot_title, func_title, sep=)
)

plot_title =  "Total replicas TotalUpTime for each idletime"
plot_hist_results(
  replicas_df_filtered,
  replicas_df_filtered$totalUptime,
  "total uptime (hour)",
  paste(plot_title, func_title, sep=)
)
plot_title = "Total replicas TotalUpTime for each idletime (excluding idletime Inf)"
plot_hist_results(
  replicas_df_filtered[replicas_df_filtered$idletime != Inf, ],
  replicas_df_filtered[replicas_df_filtered$idletime != Inf, ]$totalUptime,
  "total uptime (hour)",
  paste(plot_title, func_title, sep=)
)

plot_title =  "Total replicas TotalBusyTime for each idletime"
plot_hist_results(
  replicas_df_filtered,
  replicas_df_filtered$totalBusyTime,
  "total busy-time (hour)",
  paste(plot_title, func_title, sep=)
)
plot_title =  "Total replicas TotalBusyTime for each idletime (excluding idletime zero)"
plot_hist_results(
  replicas_df_filtered[replicas_df_filtered$idletime != 0, ],
  replicas_df_filtered[replicas_df_filtered$idletime != 0, ]$totalBusyTime,
  "total busy-time (hour)",
  paste(plot_title, func_title, sep=)
)

plot_title =  "Total replicas Efficiency for each idletime"
plot_hist_results(
  replicas_df_filtered,
  replicas_df_filtered$totalBusyTime / replicas_df_filtered$totalUptime,
  "total busy-time (hour)",
  paste(plot_title, func_title, sep=)
)
plot_title =  "Total replicas Efficiency for each idletime (excluding idletime zero)"
plot_hist_results(
  replicas_df_filtered[replicas_df_filtered$idletime != 0, ],
  replicas_df_filtered[replicas_df_filtered$idletime != 0, ]$totalBusyTime / replicas_df_filtered[replicas_df_filtered$idletime != Inf, ]$totalUptime,
  "total busy-time (hour)",
  paste(plot_title, func_title, sep=)
)

plot_title =  "Total number of replicas created for each idletime"
plot_hist_results(
  replicas_df_filtered,
  replicas_df_filtered$replicasCount,
  "number of replicas",
  paste(plot_title, func_title, sep=)
)
plot_title =  "Total number of replicas created for each idletime (excluding idletime zero)"
plot_hist_results(
  replicas_df_filtered[replicas_df_filtered$idletime != 0, ],
  replicas_df_filtered[replicas_df_filtered$idletime != 0, ]$replicasCount,
  "number of replicas",
  paste(plot_title, func_title, sep=)
)

rm(func_title)
```




# Load Data For Specific Scenario
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
results_path <- "/Users/davidquaresma/Desktop/repos/faas-simulator/results_generator_latest"
invoc_file = "_idletime0.0_tlprobp95-invocations.csv"
repl_file = "_idletime0.0_tlprobp95-replicas.csv"
sel_file = "_idletime0.0_tlprobp95-selector.csv"

results_data <- list()

technique = "baseline"
results_data$baseline_invoc = read.csv(paste(results_path, "/", technique, "/", technique, invoc_file, sep=""))
results_data$baseline_invoc <- select(transform(results_data$baseline_invoc, minResponseTime = pmin(responseTime, techniqueResponseTime)), responseTime, techniqueResponseTime, minResponseTime)
results_data$baseline_invoc$responseTimeToEvaluate <- ifelse(results_data$baseline_invoc$minResponseTime != 0, results_data$baseline_invoc$minResponseTime, results_data$baseline_invoc$responseTime)
results_data$baseline_repl = read.csv(paste(results_path, "/", technique, "/", technique, repl_file, sep=""))
results_data$baseline_sel = read.csv(paste(results_path, "/", technique, "/", technique, sel_file, sep=""))

technique = "simplehr"
results_data$shr_invoc = read.csv(paste(results_path, "/", technique, "/", technique, invoc_file, sep=""))
results_data$shr_invoc <- select(transform(results_data$shr_invoc, minResponseTime = pmin(responseTime, techniqueResponseTime)), responseTime, techniqueResponseTime, minResponseTime)
results_data$shr_invoc$responseTimeToEvaluate <- ifelse(results_data$shr_invoc$minResponseTime != 0, results_data$shr_invoc$minResponseTime, results_data$shr_invoc$responseTime)
results_data$shr_repl = read.csv(paste(results_path, "/", technique, "/", technique, repl_file, sep=""))
results_data$shr_sel = read.csv(paste(results_path, "/", technique, "/", technique, sel_file, sep=""))

technique = "delayedhr"
results_data$dhr_invoc = read.csv(paste(results_path, "/", technique, "/", technique, invoc_file, sep=""))
results_data$dhr_invoc <- select(transform(results_data$dhr_invoc, minResponseTime = pmin(responseTime, techniqueResponseTime)), responseTime, techniqueResponseTime, minResponseTime)
results_data$dhr_invoc$responseTimeToEvaluate <- ifelse(results_data$dhr_invoc$minResponseTime != 0, results_data$dhr_invoc$minResponseTime, results_data$dhr_invoc$responseTime)
results_data$dhr_repl = read.csv(paste(results_path, "/", technique, "/", technique, repl_file, sep=""))
results_data$dhr_sel = read.csv(paste(results_path, "/", technique, "/", technique, sel_file, sep=""))

technique = "gci"
results_data$gci_invoc = read.csv(paste(results_path, "/", technique, "/", technique, invoc_file, sep=""))
results_data$gci_invoc <- select(transform(results_data$gci_invoc, minResponseTime = pmin(responseTime, techniqueResponseTime)), responseTime, techniqueResponseTime, minResponseTime)
results_data$gci_invoc$responseTimeToEvaluate <- ifelse(results_data$gci_invoc$minResponseTime != 0, results_data$gci_invoc$minResponseTime, results_data$gci_invoc$responseTime)
results_data$gci_repl = read.csv(paste(results_path, "/", technique, "/", technique, repl_file, sep=""))
results_data$gci_sel = read.csv(paste(results_path, "/", technique, "/", technique, sel_file, sep=""))

rm(results_path)
rm(invoc_file)
rm(repl_file)
rm(sel_file)
rm(technique)
```

# ECDF of Latency, Replicas Alive Through Time, Workload
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
plot_ecdf("Comparison of ECDF Curves of Experiments", data.frame(
  baseline = results_data$baseline_invoc$responseTimeToEvaluate,
  rh = results_data$shr_invoc$responseTimeToEvaluate,
  rho = results_data$dhr_invoc$responseTimeToEvaluate,
  gci = results_data$gci_invoc$responseTimeToEvaluate
), 0, 25, 0, 1)

plot_replicas_alive(
  bind_rows(srh = results_data$shr_sel, baseline = results_data$baseline_sel, .id = "scenario"),
  scenario_col = "scenario",
  title = "Simple HR n Baseline Replicas Active: idletime15.0, tlprobp95"
)
plot_replicas_alive(
  bind_rows(gci = results_data$gci_sel, baseline = results_data$baseline_sel, .id = "scenario"),
  scenario_col = "scenario",
  title = "GCI n Baseline Replicas Active: idletime15.0, tlprobp95"
)
plot_replicas_alive(
  bind_rows(srh = results_data$shr_sel, drh = results_data$dhr_sel, .id = "scenario"),
  scenario_col = "scenario",
  title = "Simple n Delayed HR Replicas Active: idletime15.0, tlprobp95"
)

plot_replicas_alive(
  bind_rows(baseline = results_data$baseline_sel, rh = results_data$shr_sel, rho = results_data$dhr_sel, gci = results_data$gci_sel, .id = "scenario"),
  scenario_col = "scenario",
  title = "All TLTT Replicas Active: idletime15.0, tlprobp95"
)
```







# Playground For Exploring Funcs
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
azure_input = read.csv(paste("/Users/davidquaresma/Desktop/repos/faas-simulator/azure/", "AzureFunctionsInvocationTraceForTwoWeeksJan2021-final.csv", sep=""))

plot_requests_workload(azure_input, title="Invocations Starting At")
plot_requests_workload(azure_input, title="Invocations Ending At")

tmp <- azure_input %>%
  group_by(func) %>%
  mutate(jaja = quantile(duration, probs = 0.5, na.rm = TRUE)) %>%
  ungroup()


# check app functions rows
length(unique(azure_input$func))
azure_input %>% group_by(func) %>% summarise(count = n()) %>% arrange(desc(count))

# check apps with no zero duration
length(unique(azure_input[azure_input$duration != 0, ]$func))
azure_input[azure_input$duration != 0, ] %>% group_by(func) %>% summarise(count = n())%>% arrange(desc(count))

# check for specific app
azure_input_filter = filter(azure_input, app == "a594f92f84072b4cd031fe5283d1781a6e98f430696dec0a8e3b02eadb5fc0b8")
length(unique(azure_input_filter$func))
azure_input_filter %>% group_by(func) %>% summarise(count = n())%>% arrange(desc(count))
```

# Playground Plotting Funcs
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
# Load required libraries
library(dplyr)
library(ggplot2)
library(tidyr)

# Define your function IDs for easier reference
func_ids <- c(
  "func1" = "89d488538f940c98367ff572230106d1089868bdd379d9e2b9755b679dc186d2",
  "func2" = "b89efb5e9d1b7e5900ef441b098d4c8b01600af5e673a9f9d607b3598f0fe548",
  "func3" = "c098bb74acb70a0ea1bce98a7090169f3be59a0758389a403d77592aa56ce596",
  "func4" = "1bfbf6e1f849d22a0ece669507eb055525edf6929f273b999d865d52ea086a82",
  "func5" = "1cf618f9ee318fecbc31aa059ded8328581b9a9b092f1069b9f7679b6f89e52e",
  "func6" = "e5298aafdbabecd1465ab0eeb24d7633ac7de0284f7ee075209b119c297a3622"
)

# Method 1: Box Plot Comparison
# Prepare data for plotting
duration_data <- data.frame()
for(i in 1:length(func_ids)) {
  func_data <- filter(azure_input, func == func_ids[i])
  if(nrow(func_data) > 0) {
    temp_df <- data.frame(
      Function = names(func_ids)[i],
      Duration = func_data$duration
    )
    duration_data <- rbind(duration_data, temp_df)
  }
}

# Create box plot
p1 <- ggplot(duration_data, aes(x = Function, y = Duration, fill = Function)) +
  geom_boxplot() +
  geom_jitter(width = 0.2, alpha = 0.6) +
  labs(title = "Duration Comparison Across Functions",
       subtitle = "Box plots showing distribution of execution times",
       x = "Function",
       y = "Duration") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")

print(p1)

# Method 2: Violin Plot (shows distribution shape)
p2 <- ggplot(duration_data, aes(x = Function, y = Duration, fill = Function)) +
  geom_violin() +
  geom_boxplot(width = 0.1, alpha = 0.8) +
  labs(title = "Duration Distribution Comparison",
       subtitle = "Violin plots showing probability density of execution times",
       x = "Function",
       y = "Duration") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")

print(p2)

# Method 3: Summary Statistics Comparison
summary_stats <- duration_data %>%
  group_by(Function) %>%
  summarise(
    Count = n(),
    Mean = mean(Duration, na.rm = TRUE),
    Median = median(Duration, na.rm = TRUE),
    SD = sd(Duration, na.rm = TRUE),
    Min = min(Duration, na.rm = TRUE),
    Max = max(Duration, na.rm = TRUE),
    .groups = 'drop'
  )

print("Summary Statistics:")
print(summary_stats)

# Method 4: Bar plot of mean durations with error bars
p3 <- ggplot(summary_stats, aes(x = Function, y = Mean, fill = Function)) +
  geom_col() +
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD), 
                width = 0.2, alpha = 0.7) +
  labs(title = "Mean Duration Comparison",
       subtitle = "Error bars show ± 1 standard deviation",
       x = "Function",
       y = "Mean Duration") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")

print(p3)

# Method 5: Density plots overlaid
p4 <- ggplot(duration_data, aes(x = Duration, fill = Function)) +
  geom_density(alpha = 0.6) +
  labs(title = "Duration Density Comparison",
       subtitle = "Overlapping density curves for each function",
       x = "Duration",
       y = "Density") +
  theme_minimal() +
  facet_wrap(~Function, scales = "free")

print(p4)

# Alternative: Single plot with all densities
p5 <- ggplot(duration_data, aes(x = Duration, color = Function)) +
  geom_density(size = 1.2) +
  labs(title = "Duration Density Comparison - Overlay",
       subtitle = "All function densities on same plot",
       x = "Duration",
       y = "Density") +
  theme_minimal()

print(p5)
```

# Boxplot Visual Test
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}

plot_boxplot <- function(title, df_a, df_b, df_c, df_d, yrange, outliershape = NA) {
  return(ggplot(rbind(df_a, df_b, df_c, df_d), aes(x=scenario, y=responseTime, fill=scenario)) +
  geom_boxplot(outlier.shape = outliershape) +
  scale_fill_manual(values = c("red", "purple", "blue", "limegreen")) +
  coord_cartesian(ylim=yrange) + 
  theme(text=element_text(size=15)) +
  theme(legend.text=element_text(size=15)) +
  labs(x = "scenario", y = "latency (ms)") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank(), plot.title = element_text(hjust = 0.5)) +
  theme_bw() +
  ggtitle(title)
  )
}


df_gci_to_boxplot = data.frame(scenario = "gci", responseTime = gci$responseTimeToEvaluate)
df_rh_to_boxplot = data.frame(scenario = "rh", responseTime = rh$responseTimeToEvaluate)
df_rho_to_boxplot = data.frame(scenario = "rho", responseTime = rho$responseTimeToEvaluate)
df_van_to_boxplot = data.frame(scenario = "vanilla", responseTime = vanilla$responseTimeToEvaluate)
boxplot_plot("Boxplot for response time", df_gci_to_boxplot, df_rh_to_boxplot, df_rho_to_boxplot, df_van_to_boxplot, c(0, 5))
```
