---
title: "Synthetic Deliveries"
author: "David Ferreira Quaresma (david.quaresma@ccc.ufcg.edu.br)"
date: "set, 2025"
output: pdf_document
---

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
source("utils.R")

load_sim_results <- function(results_path, file_sufix) {
  technique = "baseline"
  parameters = "_idletimeINF_tlprobp95"
  baseline_inf_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  parameters = "_idletime900.0_tlprobp95"
  baseline_15min_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  parameters = "_idletime0.0_tlprobp95"
  baseline_zero_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))

  technique = "simplehr"
  parameters = "_idletimeINF_tlprobp95"
  simplehr_inf_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  parameters = "_idletime900.0_tlprobp95"
  simplehr_15min_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  parameters = "_idletime0.0_tlprobp95"
  simplehr_zero_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))

  technique = "simplehr"
  parameters = "_idletimeINF_tlprobp95"
  simplehr_inf_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  parameters = "_idletime900.0_tlprobp95"
  simplehr_15min_input = read.csv(paste(results_path, technique, parameters, file_sufix, sep=""))
  
  rm(sim_results_path)
  rm(technique)
  rm(parameters)
  rm(file_sufix)
  
  return(
    list(
      baseline_inf_input = baseline_inf_input,
      baseline_15min_input = baseline_15min_input,
      baseline_zero_input = baseline_zero_input,

      simplehr_inf_input = simplehr_inf_input,
      simplehr_15min_input = simplehr_15min_input,
      simplehr_zero_input = simplehr_zero_input
    )
  )
}

functions_to_plot <- c(
    "bernoulli_9510-const_5.0",
    "bernoulli_9910-const_5.0",

    "weibull_light-const_5.0",
    "weibull_medium-const_5.0",
    "weibull_heavy-const_5.0",

    "lognormal_super-const_5.0",
    "lognormal_extreme-const_5.0"
)

## Plot Arrivals Rate
#library(fitdistrplus)
#for (i in 1:length(functions_to_plot)) {
#  generated_input_filtered = filter(generated_input, func == functions_to_plot[i])
#  print(plot_requests_workload(generated_input_filtered, title=paste("Invocations for Function ", titles[i], sep="")))
  #desc_dist <- descdist(generated_input_filtered %>% pull(duration), discrete = FALSE, boot = 500)
#}
#rm(generated_input_filtered)
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
simple_results_path = "/Users/davidquaresma/Desktop/repos/faas-simulator/sim_results/simple/"
simple_df = read.csv(paste(simple_results_path, "simple_model-full-results.csv", sep="")) %>% arrange(end_timestamp)

for (i in 1:length(functions_to_plot)) {
  print(plot_histogram_fortail(
    filter(filter(simple_df, func == functions_to_plot[i]), technique == "baseline")$service_time,
    filter(filter(simple_df, func == functions_to_plot[i]), technique == "baseline")$service_time,
    "original",
    "preprocessed",
    functions_to_plot[i],
    c("#53B0E6", "#FFB86B", "#0000CC", "#CC5500", "darkblue", "saddlebrown")
  ))
}
#tmp1 <- filter(filter(simple_df, technique == "baseline"), func == "lognormal_super-const_p50")
#tmp2 <- filter(filter(simple_df, technique == "baseline"), distribution == "bernoulli")
#rm(tmp1)
#rm(tmp2)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)

scenario <- c()
baseline_response_time <- c()
hedged_requests_nodelay_response_time <- c()
hedged_requests_p95_response_time <- c()
hedged_requests_p99_response_time <- c()
near_perfect_hedged_requests_response_time <- c()
perfect_hedged_requests_response_time <- c()

imprvmnt_hedged_requests_nodelay <- c()
imprvmnt_hedged_requests_p95 <- c()
imprvmnt_hedged_requests_p99 <- c()
imprvmnt_near_perfect_hedged_requests <- c()
imprvmnt_perfect_hedged_requests <- c()
for (i in 1:length(functions_to_plot)) {
  baseline_response                     = filter(filter(simple_df, func == functions_to_plot[i]), technique == "baseline")$response_time
  hedged_requests_nodelay_response      = filter(filter(simple_df, func == functions_to_plot[i]), technique == "hedged_requests_nodelay")$response_time
  hedged_requests_p95_response          = filter(filter(simple_df, func == functions_to_plot[i]), technique == "hedged_requests_p95")$response_time
  hedged_requests_p99_response          = filter(filter(simple_df, func == functions_to_plot[i]), technique == "hedged_requests_p99")$response_time
  near_perfect_hedged_requests_response = filter(filter(simple_df, func == functions_to_plot[i]), technique == "near_perfect_hedged_requests")$response_time
  perfect_hedged_requests_response      = filter(filter(simple_df, func == functions_to_plot[i]), technique == "perfect_hedged_requests")$response_time

  scenario                                   <- append(scenario, paste(functions_to_plot[i], "response_time", sep=": "))
  baseline_response_time                     <- append(baseline_response_time,                sum(baseline_response))
  hedged_requests_nodelay_response_time      <- append(hedged_requests_nodelay_response_time, sum(hedged_requests_nodelay_response))
  hedged_requests_p95_response_time          <- append(hedged_requests_p95_response_time,     sum(hedged_requests_p95_response))
  hedged_requests_p99_response_time          <- append(hedged_requests_p99_response_time,     sum(hedged_requests_p99_response))
  near_perfect_hedged_requests_response_time <- append(near_perfect_hedged_requests_response_time, sum(near_perfect_hedged_requests_response))
  perfect_hedged_requests_response_time      <- append(perfect_hedged_requests_response_time, sum(perfect_hedged_requests_response))

  imprvmnt_hedged_requests_nodelay      <- append(imprvmnt_hedged_requests_nodelay, (1-sum(hedged_requests_nodelay_response) /sum(baseline_response))*100)
  imprvmnt_hedged_requests_p95          <- append(imprvmnt_hedged_requests_p95,     (1-sum(hedged_requests_p95_response)     /sum(baseline_response))*100)
  imprvmnt_hedged_requests_p99          <- append(imprvmnt_hedged_requests_p99,     (1-sum(hedged_requests_p99_response)     /sum(baseline_response))*100)
  imprvmnt_near_perfect_hedged_requests <- append(imprvmnt_near_perfect_hedged_requests, (1-sum(near_perfect_hedged_requests_response) /sum(baseline_response))*100)
  imprvmnt_perfect_hedged_requests      <- append(imprvmnt_perfect_hedged_requests, (1-sum(perfect_hedged_requests_response) /sum(baseline_response))*100)

  baseline_response                     = filter(filter(simple_df, func == functions_to_plot[i]), technique == "baseline")$total_time_running_functions
  hedged_requests_nodelay_response      = filter(filter(simple_df, func == functions_to_plot[i]), technique == "hedged_requests_nodelay")$total_time_running_functions
  hedged_requests_p95_response          = filter(filter(simple_df, func == functions_to_plot[i]), technique == "hedged_requests_p95")$total_time_running_functions
  hedged_requests_p99_response          = filter(filter(simple_df, func == functions_to_plot[i]), technique == "hedged_requests_p99")$total_time_running_functions
  near_perfect_hedged_requests_response = filter(filter(simple_df, func == functions_to_plot[i]), technique == "near_perfect_hedged_requests")$total_time_running_functions
  perfect_hedged_requests_response      = filter(filter(simple_df, func == functions_to_plot[i]), technique == "perfect_hedged_requests")$total_time_running_functions

  scenario                                   <- append(scenario, paste(functions_to_plot[i], "total_time_running_functions", sep=": "))
  baseline_response_time                     <- append(baseline_response_time,                sum(baseline_response))
  hedged_requests_nodelay_response_time      <- append(hedged_requests_nodelay_response_time, sum(hedged_requests_nodelay_response))
  hedged_requests_p95_response_time          <- append(hedged_requests_p95_response_time,     sum(hedged_requests_p95_response))
  hedged_requests_p99_response_time          <- append(hedged_requests_p99_response_time,     sum(hedged_requests_p99_response))
  near_perfect_hedged_requests_response_time <- append(near_perfect_hedged_requests_response_time, sum(near_perfect_hedged_requests_response))
  perfect_hedged_requests_response_time      <- append(perfect_hedged_requests_response_time, sum(perfect_hedged_requests_response))

  imprvmnt_hedged_requests_nodelay      <- append(imprvmnt_hedged_requests_nodelay, (1-sum(hedged_requests_nodelay_response) /sum(baseline_response))*100)
  imprvmnt_hedged_requests_p95          <- append(imprvmnt_hedged_requests_p95,     (1-sum(hedged_requests_p95_response)     /sum(baseline_response))*100)
  imprvmnt_hedged_requests_p99          <- append(imprvmnt_hedged_requests_p99,     (1-sum(hedged_requests_p99_response)     /sum(baseline_response))*100)
  imprvmnt_near_perfect_hedged_requests <- append(imprvmnt_near_perfect_hedged_requests, (1-sum(near_perfect_hedged_requests_response) /sum(baseline_response))*100)
  imprvmnt_perfect_hedged_requests      <- append(imprvmnt_perfect_hedged_requests, (1-sum(perfect_hedged_requests_response) /sum(baseline_response))*100)

}
rm(baseline_response)
rm(hedged_requests_nodelay_response)
rm(hedged_requests_p95_response)
rm(hedged_requests_p99_response)
rm(perfect_hedged_requests_response)
rm(perfect_hedged_requests_response)

latency_table <- data.frame(
   scenario = scenario,
   hr_nodelay = imprvmnt_hedged_requests_nodelay,
   hr_p95 = imprvmnt_hedged_requests_p95,
   hr_p99 = imprvmnt_hedged_requests_p99,
   hr_near_p = imprvmnt_near_perfect_hedged_requests,
   hr_p = imprvmnt_perfect_hedged_requests
)

kable(
  filter(latency_table, !grepl("weibull", scenario)),
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE, 
  digits = 2,
  caption = "Simple Model Latency Improvement Table All but Weibull") %>%
    add_header_above(c(" " = 1, "hedged request (hr)" = 3, "perfect (p)" = 2)) %>% 
      kable_styling(full_width = FALSE, position = "center")

kable(
  filter(latency_table, grepl("weibull", scenario)),
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE, 
  digits = 2,
  caption = "Simple Model Latency Improvement Table for Weibull") %>%
    add_header_above(c(" " = 1, "hedged request (hr)" = 3, "perfect (p)" = 2)) %>% 
      kable_styling(full_width = FALSE, position = "center")

rm(scenario)
rm(baseline_response_time)
rm(hedged_requests_nodelay_response_time)
rm(hedged_requests_p95_response_time)
rm(hedged_requests_p99_response_time)
rm(perfect_hedged_requests_response)
rm(perfect_hedged_requests_response)
rm(imprvmnt_hedged_requests_nodelay)
rm(imprvmnt_hedged_requests_p95)
rm(imprvmnt_hedged_requests_p99)
rm(imprvmnt_perfect_hedged_requests)
rm(imprvmnt_perfect_hedged_requests)
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
trace_results_path = "/Users/davidquaresma/Desktop/repos/faas-simulator/traces/generator/"
sim_results_path="/Users/davidquaresma/Desktop/repos/faas-simulator/sim_results/generator/"

file_sufix = "-invocations.csv"
loaded = load_sim_results(file_sufix)
baseline_inf_input = loaded$baseline_inf_input
baseline_15min_input = loaded$baseline_15min_input
baseline_zero_input = loaded$baseline_zero_input
simplehr_inf_input = loaded$simplehr_inf_input
simplehr_15min_input = loaded$simplehr_15min_input
simplehr_zero_input = loaded$simplehr_zero_input

baseline_inf_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_inf_input)$responseTimeToEvaluate
baseline_15min_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_15min_input)$responseTimeToEvaluate
baseline_zero_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_zero_input)$responseTimeToEvaluate
simplehr_inf_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(simplehr_inf_input)$responseTimeToEvaluate
simplehr_15min_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(simplehr_15min_input)$responseTimeToEvaluate
simplehr_zero_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(simplehr_zero_input)$responseTimeToEvaluate
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
scenario <- c()
baseline_latency <- c()
simplehr_latency <- c()
percentage <- c()
for (i in 1:length(functions_to_plot)) {
  baseline_response = filter(baseline_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  simplehr_response = filter(simplehr_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  scenario <- append(scenario, paste("func", titles[i], "idletime-INF", sep="-"))
  baseline_latency <- append(baseline_latency, sum(baseline_response))
  simplehr_latency <- append(simplehr_latency, sum(simplehr_response))
  percentage <- append(percentage, (1-sum(simplehr_response)/sum(baseline_response))*100)
  #print(summary_table(baseline_response, "baseline INF", simplehr_response,"simplehr INF"))

  baseline_response = filter(baseline_15min_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  simplehr_response = filter(simplehr_15min_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  scenario <- append(scenario, paste("func", titles[i], "idletime-15min", sep="-"))
  baseline_latency <- append(baseline_latency, sum(baseline_response))
  simplehr_latency <- append(simplehr_latency, sum(simplehr_response))
  percentage <- append(percentage, (1-sum(simplehr_response)/sum(baseline_response))*100)
  #print(summary_table(baseline_response, "baseline 15min", simplehr_response,"simplehr 15min"))
  
  baseline_response = filter(baseline_zero_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  simplehr_response = filter(simplehr_zero_input, funcID == functions_to_plot[i])$responseTimeToEvaluate
  scenario <- append(scenario, paste("func", titles[i], "idletime-zero", sep="-"))
  baseline_latency <- append(baseline_latency, sum(baseline_response))
  simplehr_latency <- append(simplehr_latency, sum(simplehr_response))
  percentage <- append(percentage, (1-sum(simplehr_response)/sum(baseline_response))*100)
  #print(summary_table(baseline_response, "baseline 15min", simplehr_response,"simplehr 15min"))
}
rm(baseline_response)
rm(simplehr_response)

total_latency_table <- data.frame(
  scenario = scenario,
  baseline = baseline_latency,
  simplehr = simplehr_latency,
  improvement = percentage
)
#print(total_latency_table)
library(knitr)
library(kableExtra)
kable(total_latency_table, 
      format = if (knitr::is_latex_output()) "latex" else "html",
      booktabs = TRUE, 
      digits = 2,
      caption = "Latency Improvement Comparison") %>%
  kable_styling(full_width = FALSE, position = "center")


rm(baseline_latency)
rm(simplehr_latency)
rm(percentage)
rm(total_latency_table)

rm(scenario)
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
file_sufix = "-replicas.csv"
loaded = load_sim_results(file_sufix)
baseline_inf_input = loaded$baseline_inf_input
baseline_15min_input = loaded$baseline_15min_input
baseline_zero_input = loaded$baseline_zero_input
simplehr_inf_input = loaded$simplehr_inf_input
simplehr_15min_input = loaded$simplehr_15min_input
simplehr_zero_input = loaded$simplehr_zero_input
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
scenario <- c()
baseline_sumuptime <- c()
simplehr_sumuptime <- c()
baseline_sumbusytime <- c()
simplehr_sumbusytime <- c()
baseline_effy <- c()
simplehr_effy <- c()
for (i in 1:length(functions_to_plot)) {
  scenario <- append(scenario, paste("func", titles[i], "idletime-INF", sep="-"))
  baseline_total = sum(filter(baseline_inf_input, funcID == functions_to_plot[i])$upTime)
  simplehr_total = sum(filter(simplehr_inf_input, funcID == functions_to_plot[i])$upTime)
  baseline_sumuptime <- append(baseline_sumuptime, baseline_total)
  simplehr_sumuptime <- append(simplehr_sumuptime, simplehr_total)
  baseline_busy = sum(filter(baseline_inf_input, funcID == functions_to_plot[i])$busyTime)
  simplehr_busy = sum(filter(simplehr_inf_input, funcID == functions_to_plot[i])$busyTime)
  baseline_sumbusytime <- append(baseline_sumbusytime, baseline_busy)
  simplehr_sumbusytime <- append(simplehr_sumbusytime, simplehr_busy)
  baseline_effy <- append(baseline_effy, baseline_busy/baseline_total*100)
  simplehr_effy <- append(simplehr_effy, simplehr_busy/simplehr_total*100)

  scenario <- append(scenario, paste("func", titles[i], "idletime-15min", sep="-"))
  baseline_total = sum(filter(baseline_15min_input, funcID == functions_to_plot[i])$upTime)
  simplehr_total = sum(filter(simplehr_15min_input, funcID == functions_to_plot[i])$upTime)
  baseline_sumuptime <- append(baseline_sumuptime, baseline_total)
  simplehr_sumuptime <- append(simplehr_sumuptime, simplehr_total)
  baseline_busy = sum(filter(baseline_15min_input, funcID == functions_to_plot[i])$busyTime)
  simplehr_busy = sum(filter(simplehr_15min_input, funcID == functions_to_plot[i])$busyTime)
  baseline_sumbusytime <- append(baseline_sumbusytime, baseline_busy)
  simplehr_sumbusytime <- append(simplehr_sumbusytime, simplehr_busy)
  baseline_effy <- append(baseline_effy, baseline_busy/baseline_total*100)
  simplehr_effy <- append(simplehr_effy, simplehr_busy/simplehr_total*100)
  
  scenario <- append(scenario, paste("func", titles[i], "idletime-zero", sep="-"))
  baseline_total = sum(filter(baseline_zero_input, funcID == functions_to_plot[i])$upTime)
  simplehr_total = sum(filter(simplehr_zero_input, funcID == functions_to_plot[i])$upTime)
  baseline_sumuptime <- append(baseline_sumuptime, baseline_total)
  simplehr_sumuptime <- append(simplehr_sumuptime, simplehr_total)
  baseline_busy = sum(filter(baseline_zero_input, funcID == functions_to_plot[i])$busyTime)
  simplehr_busy = sum(filter(simplehr_zero_input, funcID == functions_to_plot[i])$busyTime)
  baseline_sumbusytime <- append(baseline_sumbusytime, baseline_busy)
  simplehr_sumbusytime <- append(simplehr_sumbusytime, simplehr_busy)
  baseline_effy <- append(baseline_effy, baseline_busy/baseline_total*100)
  simplehr_effy <- append(simplehr_effy, simplehr_busy/simplehr_total*100)
  
}
rm(baseline_total)
rm(baseline_busy)
rm(simplehr_total)
rm(simplehr_busy)

total_effy_table <- data.frame(
  scenario = scenario,
  baseline_b = baseline_sumbusytime,
  simplehr_b = simplehr_sumbusytime,
  baseline_u = baseline_sumuptime,
  simplehr_u = simplehr_sumuptime,
  baseline_e = baseline_effy,
  simplehr_e = simplehr_effy
)
library(knitr)
library(kableExtra)
tab <- kable(
  total_effy_table,
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE,
  digits = 2,
  caption = "Replicas's Efficiency Usage"
)
tab %>%
  add_header_above(c(" " = 1, "Total Busy Time" = 2, "Total Up Time" = 2, "Efficiency" = 2)) %>%
  kable_styling(full_width = FALSE, position = "center")

rm(scenario)
rm(baseline_sumuptime)
rm(simplehr_sumuptime)
rm(baseline_sumbusytime)
rm(simplehr_sumbusytime)
rm(baseline_effy)
rm(simplehr_effy)
rm(percentage)
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
generated_input = read.csv(paste(trace_results_path, "all_generated_preprocessed-final.csv", sep=""))
#generated_input$time_readable <- as.POSIXct(generated_input$target_timestamp, origin = "2021-01-31", tz = "UTC")

file_sufix = "-invocations.csv"
loaded = load_sim_results(file_sufix)
baseline_inf_input = loaded$baseline_inf_input
baseline_15min_input = loaded$baseline_15min_input
baseline_zero_input = loaded$baseline_zero_input
simplehr_inf_input = loaded$simplehr_inf_input
simplehr_15min_input = loaded$simplehr_15min_input
simplehr_zero_input = loaded$simplehr_zero_input

baseline_inf_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_inf_input)$responseTimeToEvaluate
baseline_15min_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_15min_input)$responseTimeToEvaluate
baseline_zero_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(baseline_zero_input)$responseTimeToEvaluate
simplehr_inf_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(simplehr_inf_input)$responseTimeToEvaluate
simplehr_15min_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(simplehr_15min_input)$responseTimeToEvaluate
simplehr_zero_input$responseTimeToEvaluate = calculate_responseTimeToEvaluate(simplehr_zero_input)$responseTimeToEvaluate
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
for (i in 1:length(functions_to_plot)) {
  call_histograms(
    filter(generated_input, func == functions_to_plot[i])$duration,
    filter(baseline_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    paste(titles[i], "trace input", sep=" "),
    paste(titles[i], "baseline sim", sep=" "),
    paste("Sanity Check for ", titles[i], ": Generated vs Simulated", sep=""),
    c("#53B0E6", "#FFB86B", "#0000CC", "#CC5500", "darkblue", "saddlebrown")
  )
}
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
for (i in 1:length(functions_to_plot)) {
  call_histograms(
    filter(baseline_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    filter(simplehr_inf_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    paste(titles[i], "baseline sim", sep=" "),
    paste(titles[i], "simplehr sim", sep=" "),
    paste("Comparison under Idletime INF for ", titles[i], ": Baseline vs SimpleHR", sep=""),
    c("#FF6B6B", "#4ECDC4", "#CC0000", "#006B5B", "darkred", "darkslategray")
  )
}
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
for (i in 1:length(functions_to_plot)) {
  call_histograms(
    filter(baseline_15min_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    filter(simplehr_15min_input, funcID == functions_to_plot[i])$responseTimeToEvaluate,
    paste(titles[i], "baseline sim", sep=" "),
    paste(titles[i], "simplehr sim", sep=" "),
    paste("Comparison under Idletime 15min for ", titles[i], ": Baseline vs SimpleHR", sep=""),
    c("#FF6B6B", "#4ECDC4", "#CC0000", "#006B5B", "darkred", "darkslategray")
  )
}
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
file_sufix = "-provisioners.csv"
loaded = load_sim_results(file_sufix)
baseline_inf_input = loaded$baseline_inf_input
baseline_15min_input = loaded$baseline_15min_input
baseline_zero_input = loaded$baseline_zero_input
simplehr_inf_input = loaded$simplehr_inf_input
simplehr_15min_input = loaded$simplehr_15min_input
simplehr_zero_input = loaded$simplehr_zero_input
```

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'}
### Plot Replicas Alive
#The plots show the number of active replicas over time for baseline vs simpleHR across all idletime configurations. The purpose is to understand whether simpleHR keeps more replicas alive and how that impacts resource usage. As expected for every function, simplehr requires more simultaneous replicas. Fun observation is how idletime inf impact varies according to the function distribution latency.  

for (i in 1:length(functions_to_plot)) {
  print(
    plot_replicas_alive(
      bind_rows(
        baseline_inf = filter(baseline_inf_input, funcID == functions_to_plot[i]),
        simplehr_inf = filter(simplehr_inf_input, funcID == functions_to_plot[i]),
        baseline_15min = filter(baseline_15min_input, funcID == functions_to_plot[i]),
        simplehr_15min = filter(simplehr_15min_input, funcID == functions_to_plot[i]),
        baseline_zero = filter(baseline_zero_input, funcID == functions_to_plot[i]),
        simplehr_zero = filter(simplehr_zero_input, funcID == functions_to_plot[i]),
        .id = "scenario"
      ),
      c("baseline_inf", "simplehr_inf", "baseline_15min", "simplehr_15min", "baseline_zero", "simplehr_zero"),
      scenario_col = "scenario",
      title = paste(titles[i], ": Replicas Active for Baseline vs SimpleHR", sep="")
    )
  )
}
```
