---
title: "Trace Preparation"
author: "David Ferreira Quaresma (david.quaresma@ccc.ufcg.edu.br)"
date: "ago, 2025"
output: pdf_document
---

# Load Utils
```{r setup, include=FALSE}
source("utils.R")
```

# Load Azure Dataset
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
# Load Azure Functions
start_time <- Sys.time()
data_path = "/Users/davidquaresma/Desktop/repos/faas-simulator/traces/azure/"
file_name = "AzureFunctionsInvocationTraceForTwoWeeksJan2021"

inv2021 = read.csv(paste(data_path, file_name, ".csv", sep=""), header = TRUE)
inv2021_preprocessed <- preprocess_data(inv2021)
# save processed data
write.csv(inv2021_preprocessed, file = paste(data_path, file_name, "-final.csv", sep=""), row.names = FALSE)

end_time <- Sys.time()
azure_load_duration <- as.numeric(end_time - start_time, units = "secs")
print(paste("Azure Functions Load Time: ", azure_load_duration, sep=""))
```

# Load Generator Dataset
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
# Load Generated Functions
start_time <- Sys.time()
data_path = "/Users/davidquaresma/Desktop/repos/faas-simulator/traces/generator/"

bernoulli_constante = read.csv(paste(data_path, "latency_bernoulli-arrival_constant", ".csv", sep=""), header = TRUE)
bernoulli_poisson = read.csv(paste(data_path, "latency_bernoulli-arrival_poisson", ".csv", sep=""), header = TRUE)
weibull_constante = read.csv(paste(data_path, "latency_weibull-arrival_constant", ".csv", sep=""), header = TRUE)
weibull_poisson = read.csv(paste(data_path, "latency_weibull-arrival_poisson", ".csv", sep=""), header = TRUE)
logNormal_constante = read.csv(paste(data_path, "latency_logNormal-arrival_constant", ".csv", sep=""), header = TRUE)
logNormal_poisson = read.csv(paste(data_path, "latency_logNormal-arrival_poisson", ".csv", sep=""), header = TRUE)

all_generated <- do.call(rbind,
  list(bernoulli_constante, bernoulli_poisson, weibull_constante, weibull_poisson, logNormal_constante, logNormal_poisson)
)
rm(bernoulli_constante, bernoulli_poisson, weibull_constante, weibull_poisson, logNormal_constante, logNormal_poisson)
all_generated_preprocessed <- preprocess_data(all_generated)

# save processed data
write.csv(all_generated_preprocessed, file = paste(data_path, "all_generated_preprocessed", "-final.csv", sep=""), row.names = FALSE)

end_time <- Sys.time()
generated_load_duration <- as.numeric(end_time - start_time, units = "secs")
print(paste("Generated Functions Load Time: ", generated_load_duration, sep=""))
```

# Azure Functions Plot
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
functions_to_plot <- c(
  "155e47f8e7f751d0c845049456d01832013c61336a8cd85901330ac821a71534", # 535667 -> 535667
  "8ef9c2c907e9cd5fb4b5cb3bfbebca6d9a01bb1f65a0f476e3914cae25bd2aae", # 212755 -> 161085 (had zero duration entries)
  "cc5bb2108cc7daf53f9728ad21f661a8ef9c8b36284bacfcb712e2be87eef842", # 142856 -> 142856
  "4753d9ffc8a362eadfb27498581969561c0ddbec7257759dbcb9936e506aff82" # 124143 -> 124143
#  "89d488538f940c98367ff572230106d1089868bdd379d9e2b9755b679dc186d2", # 76093 -> 76093
#  "bd5be891d0d10fbc3c59215d5f8159ea496433bc41adba7d8d10ea21d35c3e3a", # 116130 -> 73464 (had zero duration entries)
#  "30aa434528bc68ee07745ee7be3a0bdb33d58961fdc8460ce5b5b46b4def96e8", # 71759 -> 71759
#  "b89efb5e9d1b7e5900ef441b098d4c8b01600af5e673a9f9d607b3598f0fe548", # 63506 -> 63506
#  "8e5f533dbf1092f56ac6c7542ef3bdec4661bd442c9b5e7537fabc7b8c03f5a8", # 53263 -> 53263
#  "c098bb74acb70a0ea1bce98a7090169f3be59a0758389a403d77592aa56ce596", # 41333 -> 41333
#  "eefb3a7b86d12c2676276a5dde28099ef6f546a60e5b78e0a1c2b7221baf154d"  # 41333 -> 3107 (had too many zero duration entries)
)
  
titles <- c(
  "func w/ suffix 534",
  "func w/ suffix aae", 
  "func w/ suffix 842",
  "func w/ suffix f82"
#  "func w/ suffix 6d2",
#  "func w/ suffix e3a", 
#  "func w/ suffix 6e8",
#  "func w/ suffix 548",
#  "func w/ suffix 5a8",
#  "func w/ suffix 596",
#  "func w/ suffix 54d"
)

for (i in 1:length(functions_to_plot)) {
  print(
    call_histograms(
      filter(inv2021, func == functions_to_plot[i])$duration,
      filter(inv2021_preprocessed, func == functions_to_plot[i])$duration,
      "original",
      "preprocessed",
      titles[i],
      c("#FF6B6B", "#4ECDC4", "#CC0000", "#006B5B", "darkred", "darkslategray")
    )
  )
}
```

# Generated Functions Plot
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
functions_to_plot <- c(
  "constant-bernoulli-func",
  "constant-weibull-func",
  "constant-logNormal-func"
 #"poisson-bernoulli-func",
 #"poisson-weibull-func",
 #"poisson-logNormal-func",
)
  
titles <- c(
  "constant-bernoulli func",
  "constant-weibull func",
  "constant-logNormal func"
  #"poisson-bernoulli func",
  #"poisson-weibull func",
  #"poisson-logNormal func"
)

for (i in 1:length(functions_to_plot)) {
  print(
    call_histograms(
      filter(all_generated, func == functions_to_plot[i])$duration,
      filter(all_generated_preprocessed, func == functions_to_plot[i])$duration,
      "original",
      "preprocessed",
      titles[i],
      c("#53B0E6", "#FFB86B", "#0000CC", "#CC5500", "darkblue", "saddlebrown")
    )
  )
}
```

